head:
    # 网站图标 多个随机
    favicon: "/img/36.jpg"


img:
    # 头像 多个随机
    avatar: "/img/36.jpg"
    # 首页左边图片 多个随机
    left_pic: 
      - "/img/34.jpg"
    # 首页右边图片 多个随机 (移动端不显示)
    right_pic:
      - "/img/14.jpg"
    # 默认文章背景 多个随机
    post_thumbnail: 
      - "/img/1.jpg"
      - "/img/2.jpg"
      - "/img/3.jpg"
      - "/img/4.jpg"
      - "/img/5.jpg"
      - "/img/6.jpg"
      - "/img/7.jpg"
      - "/img/8.jpg"
      - "/img/9.jpg"
      - "/img/10.jpg"
      - "/img/11.jpg"
      - "/img/12.jpg"
      - "/img/13.jpg"
      - "/img/14.jpg"
      - "/img/15.jpg"
      - "/img/16.jpg"
      - "/img/17.jpg"
      - "/img/18.jpg"
      - "/img/19.jpg"
      - "/img/20.jpg"
      - "/img/21.jpg"
      - "/img/22.jpg"
      - "/img/23.jpg"
      - "/img/24.jpg"
      - "/img/25.jpg"
      - "/img/26.jpg"
      - "/img/27.jpg"
      - "/img/28.jpg"
      - "/img/29.jpg"
      - "/img/30.jpg"
      - "/img/31.jpg"
      - "/img/32.jpg"
      - "/img/33.jpg"
      - "/img/34.jpg"
      - "/img/35.jpg"
      - "/img/36.jpg"
    # 侧边抽屉头部图片 多个随机
    drawerHeaderBg:
      - "/img/31.jpg"

uiux:
    #标语 多个随机
    slogan: "一直宅下去！"
    #主色 多个随机
    defaultPrimaryColor: "blue"
    #强调色 多个随机
    defaultAccentColor: "red"

#评论 (定义多个 就会显示多个评论框)
comment:
#   duoshuo:
#       shortName: "xxx"
    disqus:
        shortName: "jishuzai666"

#侧边抽屉
Drawer:
    -
      #标题
      title: 首页
      #类型: 站内链接
      type: sitelink
      #链接: 根目录
      href: /
      #图标
      icon: home
    -
      #标题: hr（此处不会显示）
      title: hr
      #类型: 分割线
      type: hr
    -
      #标题: 搜索
      title: 搜索
      #类型: 站内链接
      type: sitelink
      #链接: 搜索功能
      href: /search/
      #图标
      icon: search
    -
      #标题: 联系我
      title: 联系我
      #图标
      icon: contact_phone
      #子目录
      nested: 
        - 
          #标题: Email
          title: 邮箱
          #站外链接
          type: link
          #链接
          href: mailto:1132053388@qq.com
          #图标
          icon: mail_outline

#取色器(在侧边抽屉)
colorPicker: true

#首页工具栏移动端不显示（在首页第2张卡片）

#底部
footer:
  # 底部中间(移动端有所不同)  多个随机
  -
    "技术改变技术宅"
  # 底部右间(移动端有所不同)  多个随机
  -
    -
      只是想写点东西！
